# Generated by Django 2.2.5 on 2020-01-21 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200115_2142'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
