# Generated by Django 2.2.5 on 2020-01-29 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_category_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateField(default='2020-01-20'),
        ),
        migrations.AlterModelTable(
            name='category',
            table=None,
        ),
    ]
